# Base Image
FROM ghcr.io/missourimrdt/autonomy-jetpack:latest

# Install Variables
ARG L4T_MAJOR="35"
ARG L4T_MINOR="3"
ARG L4T_PATCH="1"
ARG L4T_BASE="l4t-jetpack"
ARG ZED_MAJOR="4"
ARG ZED_MINOR="0"
ARG CMAKE_VERSION="3.24.3"
ARG OPENCV_VERSION="4.8.0"
ARG QUILL_VERSION="v3.3.1"
ARG GTEST_VERSION="v1.14.0"
ARG MAV_VERSION="v1.4.16"

# Set Labels
LABEL authors="Missouri S&T Mars Rover Design Team"
LABEL maintainer="Mars Rover Design Team <marsrover@mst.edu>"
LABEL org.opencontainers.image.source=https://github.com/missourimrdt/drone_autonomy_software
LABEL org.opencontainers.image.licenses=GPL-3.0-only
LABEL org.opencontainers.image.version="v24.1.0"
LABEL org.opencontainers.image.description="Docker Image for ${L4T_BASE} ${L4T_MAJOR}.${L4T_MINOR}.${L4T_PATCH} with CUDA ${CUDA_MAJOR}.${CUDA_MINOR}, ZED SDK ${ZED_MAJOR}.${ZED_MINOR}, OpenCV ${OPENCV_VERSION}, Quill ${QUILL_VERSION}, and Google Test ${GTEST_VERSION}."

# Set Non-Interactive Mode
ARG DEBIAN_FRONTEND=noninteractive

# Set Jetson Streaming Evironment Variables
ENV LOGNAME root

# Set L4T Version
RUN echo "# R${L4T_MAJOR} (release), REVISION: ${L4T_MINOR}.${L4T_PATCH}" > /etc/nv_tegra_release

# Install Required Ubuntu Packages
RUN apt-get update && apt-get install --no-install-recommends -y \
    python3-future colordiff

# Set Working Directory
WORKDIR /opt

# Install MAVSDK from Source
RUN git clone --depth 1 --branch ${MAV_VERSION} https://github.com/mavlink/mavsdk.git && \
    cd mavsdk && \
    git submodule update --init --recursive && \
    cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -Bbuild/default -H. && \
    sudo cmake --build build/default --target install && \
    cd .. && \
    rm -rf mavsdk

# Enable Make Threads
RUN echo 'export MAKEFLAGS=-j$(($(grep -c "^processor" /proc/cpuinfo) - 1))' >> .bashrc

# Delete Autonomy Software Repository
RUN rm -rf /opt/Autonomy_Software

# Clone Drone_Autonomy Software Repository
RUN git clone --recurse-submodules -j8 https://github.com/MissouriMRDT/Drone_Autonomy_Software.git

# Set Working Directory
WORKDIR /opt/Drone_Autonomy_Software/
