## MRDT Layer
FROM ghcr.io/missourimrdt/autonomy-focal:latest AS mrdt

# Install Variables
ARG UBUNTU_MAJOR="20"
ARG CUDA_MAJOR="11"
ARG CUDA_MINOR="7"
ARG CUDA_PATCH="0"
ARG ZED_MAJOR="4"
ARG ZED_MINOR="0"
ARG CMAKE_VERSION="3.24.3"
ARG OPENCV_VERSION="4.8.0"
ARG QUILL_VERSION="v3.3.1"
ARG GTEST_VERSION="v1.14.0"
ARG MAV_VERSION="v1.4.3"

# Set Labels
LABEL authors="Missouri S&T Mars Rover Design Team"
LABEL maintainer="Mars Rover Design Team <marsrover@mst.edu>"
LABEL org.opencontainers.image.source=https://github.com/missourimrdt/drone_autonomy_software
LABEL org.opencontainers.image.licenses=GPL-3.0-only
LABEL org.opencontainers.image.version="v24.1.0"
LABEL org.opencontainers.image.description="Docker Image for Ubuntu ${UBUNTU_MAJOR}.${UBUNTU_MINOR} with CUDA ${CUDA_MAJOR}.${CUDA_MINOR}, ZED SDK ${ZED_MAJOR}.${ZED_MINOR}, OpenCV ${OPENCV_VERSION}, Quill ${QUILL_VERSION}, Google Test ${GTEST_VERSION}, and MAVSDK ${MAV_VERSION}."

# Set Non-Interactive Mode
ARG DEBIAN_FRONTEND=noninteractive

# Set NVIDIA Driver Enviroment Variables
ENV NVIDIA_DRIVER_CAPABILITIES \
    ${NVIDIA_DRIVER_CAPABILITIES:+$NVIDIA_DRIVER_CAPABILITIES,}compute,video,utility,graphics

# Set CUDA Version
RUN echo "CUDA Version ${CUDA_MAJOR}.${CUDA_MINOR}.0" > /usr/local/cuda/version.txt

# Install Required Ubuntu Packages
RUN apt-get update && apt-get install --no-install-recommends -y \
    python3-future colordiff

# Set Working Directory
WORKDIR /opt

# Install MAVSDK from Source
RUN git clone --depth 1 --branch ${MAV_VERSION} https://github.com/mavlink/mavsdk.git && \
    cd mavsdk && \
    git submodule update --init --recursive && \
    cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -Bbuild/default -H. && \
    sudo cmake --build build/default --target install && \
    cd .. && \
    rm -rf mavsdk

# Enable Make Threads
RUN echo 'export MAKEFLAGS=-j$(($(grep -c "^processor" /proc/cpuinfo) - 1))' >> /root/.bashrc

# Fix Perl Locale Error
RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && locale-gen
ENV LANG en_US.UTF-8  
ENV LANGUAGE en_US:en  
ENV LC_ALL en_US.UTF-8  

# Enable Cowsay.
RUN echo '/usr/games/fortune | /usr/games/cowsay -f `ls /workspaces/Drone_Autonomy_Software/data/Cowsay_Cows/*.cow | shuf -n 1`' >> /root/.bashrc

# Delete Autonomy Software Repository
RUN rm -rf /opt/Autonomy_Software

# Clone Drone Autonomy Software Repository
RUN git clone --recurse-submodules -j8 https://github.com/MissouriMRDT/Drone_Autonomy_Software.git

# Set Working Directory
WORKDIR /opt/Drone_Autonomy_Software/

## PX4 Gazebo Headless Layer
FROM mrdt AS px4

ARG PX4_VERSION="v1.13.3"
ARG PX4_INSTALL="px4-gazebo-headless/"

ENV WORKSPACE_DIR /root
ENV FIRMWARE_DIR ${WORKSPACE_DIR}/Firmware
ENV SITL_RTSP_PROXY ${WORKSPACE_DIR}/sitl_rtsp_proxy

ENV DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true
ENV DISPLAY :99
ENV LANG C.UTF-8

RUN apt-get update && \
    apt-get install -y bc \
                       gazebo9 \
                       gstreamer1.0-plugins-bad \
                       gstreamer1.0-plugins-base \
                       gstreamer1.0-plugins-good \
                       gstreamer1.0-plugins-ugly \
                       iproute2 \
                       libeigen3-dev \
                       libgazebo9-dev \
                       libgstreamer-plugins-base1.0-dev \
                       libgstrtspserver-1.0-dev \
                       libopencv-dev \
                       libroscpp-dev \
                       protobuf-compiler \
                       python3-jsonschema \
                       unzip \
                       xvfb && \
    apt-get -y autoremove && \
    apt-get clean autoclean && \
    rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*

RUN pip3 install --upgrade pip && \
    pip3 install empy \
                 future \
                 jinja2 \
                 kconfiglib \
                 packaging \
                 pyros-genmsg \
                 toml \
                 pyyaml

RUN git clone --recurse-submodules -j8 --depth 1 --branch ${PX4_VERSION} https://github.com/PX4/PX4-Autopilot.git ${FIRMWARE_DIR}

COPY ${PX4_INSTALL}edit_rcS.bash ${WORKSPACE_DIR}
COPY ${PX4_INSTALL}entrypoint.sh ${WORKSPACE_DIR}/entrypoint.sh
RUN chmod +x ${WORKSPACE_DIR}/entrypoint.sh

RUN ["/bin/bash", "-c", " \
    cd ${FIRMWARE_DIR} && \
    DONT_RUN=1 make px4_sitl gazebo && \
    DONT_RUN=1 make px4_sitl gazebo \
"]

COPY ${PX4_INSTALL}sitl_rtsp_proxy ${SITL_RTSP_PROXY}
RUN cmake -B${SITL_RTSP_PROXY}/build -H${SITL_RTSP_PROXY}
RUN cmake --build ${SITL_RTSP_PROXY}/build
